#!/usr/bin/env ruby
require_relative "../../lib/ferret"

run_every_time do
  bash(name: :curl, stdin: <<-'EOF')
   curl --fail https://splunk.herokai.com/en-US/account/login
  EOF
end

run forever: true