#!/usr/bin/env ruby
require_relative "../../lib/ferret"

run_every_time do
  bash(name: :get, stdin: <<-'EOF')
   curl --fail "https://l2met:${METRICS_TOKEN}@l2met-next.herokuapp.com/metrics/uptime?limit=1&resolution=5" 
  EOF
end

run forever: true
