monitors_dns_resolve: bundle exec monitors/dns/resolve
monitors_ferret_dash: bundle exec monitors/ferret/dash
monitors_git_bamboo: bundle exec monitors/git/bamboo
monitors_git_cedar: bundle exec monitors/git/cedar
monitors_heroku_addons: bundle exec monitors/heroku/addons
monitors_heroku_apps: bundle exec monitors/heroku/apps
monitors_heroku_run: bundle exec monitors/heroku/run
monitors_http_bamboo: bundle exec monitors/http/bamboo
monitors_http_cedar: bundle exec monitors/http/cedar
monitors_http_curl: bundle exec monitors/http/curl
monitors_http_endpoint: bundle exec monitors/http/endpoint
monitors_http_recurl: bundle exec monitors/http/recurl
monitors_l2met_health: bundle exec monitors/l2met/health
monitors_l2met_metric: bundle exec monitors/l2met/metric
monitors_perf_cpu: bundle exec monitors/perf/cpu
monitors_perf_disk: bundle exec monitors/perf/disk
monitors_perf_network: bundle exec monitors/perf/network
monitors_splunk_health: bundle exec monitors/splunk/health
monitors_splunk_search: bundle exec monitors/splunk/search
web: bundle exec thin start -p $PORT
