monitors_dns_resolve: monitors/dns/resolve
monitors_ferret_dash: monitors/ferret/dash
monitors_git_clone: monitors/git/clone
monitors_heroku_addons: monitors/heroku/addons
monitors_heroku_apps: monitors/heroku/apps
monitors_heroku_run: monitors/heroku/run
monitors_http_bamboo: monitors/http/bamboo
monitors_http_cedar: monitors/http/cedar
monitors_http_curl: monitors/http/curl
monitors_http_endpoint: monitors/http/endpoint
monitors_http_recurl: monitors/http/recurl
monitors_l2met_health: monitors/l2met/health
monitors_l2met_metric: monitors/l2met/metric
monitors_perf_cpu: monitors/perf/cpu
monitors_perf_disk: monitors/perf/disk
monitors_perf_network: monitors/perf/network
monitors_splunk_ferret_sublime_workspace: monitors/splunk/ferret.sublime-workspace
monitors_splunk_health: monitors/splunk/health
monitors_splunk_search: monitors/splunk/search
monitors_ssh_fingerprint: monitors/ssh/fingerprint
monitors_ssh_path: monitors/ssh/path
web: bundle exec thin start -p $PORT
