<<<<<<< HEAD
monitors_dns_resolve: monitors/dns/resolve
monitors_git_clone: monitors/git/clone
monitors_heroku_addons: monitors/heroku/addons
monitors_heroku_apps: monitors/heroku/apps
monitors_heroku_run: monitors/heroku/run
monitors_http_bamboo: monitors/http/bamboo
monitors_http_cedar: monitors/http/cedar
monitors_http_curl: monitors/http/curl
monitors_http_endpoint: monitors/http/endpoint
monitors_http_recurl: monitors/http/recurl
monitors_perf_cpu: monitors/perf/cpu
monitors_perf_disk: monitors/perf/disk
monitors_perf_network: monitors/perf/network
monitors_ssh_fingerprint: monitors/ssh/fingerprint
monitors_ssh_path: monitors/ssh/path
=======
monitors_dns_resolve: ./monitors/dns/resolve
monitors_git_clone: ./monitors/git/clone
monitors_heroku_addons: ./monitors/heroku/addons
monitors_heroku_apps: ./monitors/heroku/apps
monitors_heroku_run: ./monitors/heroku/run
monitors_http_bamboo: ./monitors/http/bamboo
monitors_http_cedar: ./monitors/http/cedar
monitors_http_curl: ./monitors/http/curl
monitors_http_endpoint: ./monitors/http/endpoint
monitors_http_recurl: ./monitors/http/recurl
monitors_perf_cpu: ./monitors/perf/cpu
monitors_perf_disk: ./monitors/perf/disk
monitors_perf_network: ./monitors/perf/network
monitors_ssh_fingerprint: ./monitors/ssh/fingerprint
monitors_ssh_path: ./monitors/ssh/path
>>>>>>> f25c1b8238db4fd0d9429b43947f0b83c546033a
web: bundle exec thin start -p $PORT
