#!/usr/bin/env ruby
require_relative "../../lib/ferret"

run_every_time do
  bash(name: :curl0, timeout: 3900, stdin: <<-'EOSH')
    curl --fail http://$APP-bamboo-0.herokuapp.com -v
  EOSH
  bash(name: :curl1, timeout: 3900, stdin: <<-'EOSH')
    curl --fail http://$APP-bamboo-1.herokuapp.com -v
  EOSH
  bash(name: :curl2, timeout: 3900, stdin: <<-'EOSH')
    curl --fail http://$APP-bamboo-2.herokuapp.com -v
  EOSH
end

run forever: true
