#!/usr/bin/env ruby
require_relative "../../lib/ferret"

run_every_time do
  bash(name: :curl, timeout: 3900, stdin: <<-'EOSH')
    curl --fail http://$APP-cedar.herokuapp.com -v
  EOSH
end

run forever: true
