#!/usr/bin/env ruby
require_relative "../../lib/ferret"

run_every_time do
  bash(name: :curl, timeout: 3900, stdin: <<-'EOSH')
    ENDPOINT=$(curl -u ":$HEROKU_API_KEY" -s https://api.heroku.com/apps/$APP-cedar-endpoint/ssl-endpoints | grep cname | cut -d"\"" -f4)
    curl -ik --fail https://$ENDPOINT -H "Host: www.${APP}-cedar-endpoint.com"
  EOSH
end

run forever: true
