#!/usr/bin/env ruby
require_relative "../../lib/ferret"

run_interval 10 do 
  bash(name: :consider_restart, timeout: 50, stdin: <<-'EOSH')
    heroku restart --app $APP-http
  EOSH
end

run_every_time do
  bash(name: :curl, timeout: 30, stdin: <<-'EOSH')
    set -x
    curl --fail http://${APP}-http.herokuapp.com -v
  EOSH
end

run forever: true