#!/usr/bin/env ruby

require_relative "../../lib/ferret"

bash(name: :blowfish, stdin: <<-'EOF')
  openssl speed rsa -elapsed -mr
EOF

bash(name: :restart, stdin: <<-'EOF')
  heroku restart monitors_perf_cpu -a $APP
EOF


run forever:true
