#!/usr/bin/env ruby

require_relative "../../lib/ferret"

bash(name: :dd, stdin: <<-'EOF')
  rm -f /tmp/o
  if [ "$(uname)" = "Darwin" ]; then
    dd if=/dev/zero of=/tmp/o bs=10000000 count=20
  else
    dd if=/dev/zero of=/tmp/o bs=10M count=20 oflag=direct,sync
  fi
EOF

bash(name: :restart, stdin: <<-'EOF')
  heroku restart monitors_perf_disk -a $APP
EOF

