#!/usr/bin/env ruby
require_relative "../../lib/ferret"

run_every_time do
  bash(name: :add, pattern: /Adding heroku-postgresql:dev (to|on) #{ENV["APP"]}-addons/, stdin: <<-EOF)
    heroku addons:add heroku-postgresql:dev -a $APP-addons
  EOF

  bash(name: :remove, pattern: /Removing .* done/, stdin: <<-EOF)
    # remove all postgres addons
    heroku addons --app $APP-addons | grep heroku-postgresql:dev | cut -d" " -f3 | xargs -I {} heroku addons:remove {} --app $APP-addons --confirm $APP-addons
  EOF
end

run forever: true
