#!/usr/bin/env ruby
require_relative "../../lib/ferret"

run_interval(30) do
  bash(name: :clone, pattern: /cloned an empty repository/, stdin: <<-'EOF')
    rm -rf ./app
    git clone git@heroku.com:$APP.git ./app
  EOF
end

run forever: true
