#!/usr/bin/env ruby
require_relative "../../lib/ferret"

bash(name: :resolve, stdin: <<-'EOF')
  nc redis-19595.us-east-1-4.1.ec2.garantiadata.com 19595 -w 1
EOF

bash(name: :restart, stdin: <<-'EOF')
  heroku restart monitors_dns_resolve -a $APP
EOF

